<?php die('Unauthorized access.'); ?>a:64:{s:2:"id";s:3:"914";s:4:"type";s:8:"document";s:11:"contentType";s:9:"text/html";s:9:"pagetitle";s:54:"Images in Action. Photography, Gesture, Performativity";s:9:"longtitle";s:54:"Images in Action. Photography, Gesture, Performativity";s:11:"description";s:0:"";s:5:"alias";s:16:"images-in-action";s:15:"link_attributes";s:0:"";s:9:"published";s:1:"1";s:8:"pub_date";s:1:"0";s:10:"unpub_date";s:1:"0";s:6:"parent";s:3:"908";s:8:"isfolder";s:1:"0";s:9:"introtext";s:0:"";s:7:"content";s:24915:"{"richtext":"<p>We ought to start by examining the hands. “How astonishing it is that the hand can express so much! Yet what is more astonishing is that the hand embodies so little. Just look at our hands: what unhewn, bulky, lazy blocks they are. What unprocessed material they are, always identical and always similar to each other, with no play or internal life,”<a href=\"#sdfootnote1sym\" name=\"sdfootnote1anc\"><sup>1</sup></a> remarked Prince Sergey Volkonsky in his 19th century description of the stage methods developed by François Delsarte, creator of a codified system of acting techniques. Volkonsky devotes his subsequent reflections to the means by which this unruly “cluster” of the hand not only acquires the necessary expressive power, but, perhaps more importantly, is unleashed from this state of meaningless raw material and (through the proper formatting) begins to communicate very specific meanings, here ascribed to illustrations that demonstrate the appropriate modeling of the gesture. It is worth noting that most of the world’s theatrical systems contain a tradition of disciplined approach to the hands: they are subjected to codified exercises and acquire the ability to speak through the study of a formal language. Traces of this can likely be found in the popular saying regarding bad actors who “don’t even know what to do with their hands on stage.” This is an important clue: it seems that a hand that is devoid of form when viewed in public threatens the existing order and remains ready to engage in subversive activity.</p>\n<p>It is precisely hands that became the main — or at least the most spectacular — actors in the performative symposium “Gesture Toward Photography,” held by Krzysztof Pijarski at the Zachęta Gallery in Warsaw in October 2013.<a href=\"#sdfootnote2sym\" name=\"sdfootnote2anc\"><sup>2</sup></a> Comprising six intensive sessions, the two-day event became a peculiar experiment designed to test an alternative model for producing knowledge (with a particular focus, of course, on the knowledge both generated by — and created for — the photographic image). The accompanying program explains that “In place of a situation where the speaker, separated from the audience, shares his already prepared knowledge, the performative symposium proposes a meeting of several people — artists and theorists — to discuss specific photographs in any format, books or contact sheets, in order to ‘discover’ or explore them — for each other and for the gathered audience. The process of discovering/exploring the images will be carried out not only through a discussion, but essentially, via the exchange of gestures: by pointing a finger, juxtaposing, cropping, inscribing, outlining, etc. — the whole repertoire of responses to the images which the body has at its disposal.”<a href=\"#sdfootnote3sym\" name=\"sdfootnote3anc\"><sup>3</sup></a> In effect, the symposium became more than just an interesting subversion of the existing conference standard: it resulted in several meaningful shifts involving the categories of gesture and visuality itself. It is precisely this shift that I wish to explore in the commentary below.</p>\n<p>Held in an empty white room, the symposium immediately revealed its theatrical potential; or, rather, it ostentatiously established a performative frame for the events. The participants of the discussion, meaning teams that invariably included Krzysztof Pijarski, artists working in the medium of photography, and an interlocutor, sat at a round wooden table, while the audience took their seats with their backs to the group, viewing the discussion on a screen linked to a camera placed over the table. The audience heard the participants while also observing their hands, which performed a variety of operations on the discussed images placed before them. Each conversation held at the symposium was presented to the audience in this manner and recorded as a film. I would like to examine several themes that emerged from the encounters as held in this format: namely the relationship between the image and gesture that formed during the filming of the event, the peculiarly-planned circumstances for the distribution of knowledge, and the photographic work of Paweł Bownik, whom I accompanied as an interlocutor on one panel.</p>\n<p>The characteristic feature of the hands depicted in the symposium recordings are their vitality and their readiness for incessant action. Very rarely do they rest motionlessly; even then they clearly reveal the impulses that will momentarily result in further movement. Though the individual films depicting each conversation differ in terms of their dynamics, viewing them in their entirety allows one to compile a catalog of recurring gestures. The catalogue could include, more or less, the following: the touching of visual materials; smoothing them, holding, moving, arranging or scattering them; gestures also associated with the act of delivering or explaining one’s thoughts to someone (in various manners: typically with the palms facing inwards or upwards), responding to another person’s thoughts or words, with the hands moving in and out of the picture; and finally, ostentatiously theatrical hands, self-conscious of being filmed (e.g., the hands sliding underneath a convex photograph in the panel devoted to the work of Grospierre).</p>\n<p>The dynamics of these gestures, as depicted in the recordings of the hands, can be examined from the perspective of the Brechtian concept of the Gestus, that is, the “complex of gestures and expressions that form the basis of various actions among people, and the behavior common to all involved in these actions (…) or the complex of gestures and expressions that, when performed by a person, elicit specific behavior in others, or, finally, the demeanor of an individual person. (…) Gestus always denotes the attitude people have toward each other.”<a href=\"#sdfootnote4sym\" name=\"sdfootnote4anc\"><sup>4</sup></a> It is thus a dynamic web of interactions that provides insight into social relations, or at least into the dynamic of relations that emerges among a group of people.</p>\n<p>The physical gestures performed as a part of the Gestuses operating within the recordings are often linked to a very specific action in relation to the photographic images. For example, participants of the various panels cut the photographs and arrange them in space (Grospierre), draw on them using markers (Bownik), and point out particular elements in them (Wilczyk and Janicka). The conversation of hands observed on the screen somehow elucidates, explains, or “unpacks” the artworks placed on the table (gradual and methodical “unpacking” being the main discursive strategy of the symposium); by performing intuitively comprehensible gestures, the hands weave a clear web of communication.</p>\n<p>The image presented in this manner is utterly incomplete. What made the recordings screened at the Zachęta Gallery unique, and facilitated a shift in the field of knowledge and visuality, was the result achieved within the assumed framework of the experiment and — in keeping with its logic — one achieved only in practice. This is because the aforementioned clear gestures were accompanied by completely unclassifiable conversations that comprised a peculiar form of anti-iconography. The recorded discussions in fact reveal a “gestural surplus,” this unnameable feverish activity of the hands. Moreover, these gestures usually contradict the words accompanying them in the conversation: the former are completely inadequate to the latter. The image of the gestural conversation is thus replete with images of fingertips being picked at, hands being rubbed, clumsy, aimless movements, crossed fingers, and reflexive tapping. The actions of the hands — irrespective of the situation, words, and gestures — have no direct relation to anything else and cannot be confined to the above-mentioned concept of the Gestus. The gestures performed by the mutinous hands are more easily described using the concept of social choreography,<a href=\"#sdfootnote5sym\" name=\"sdfootnote5anc\"><sup>5</sup></a> which seems much broader and encompasses the entirety of movement connections within a community (or, in this case, a microcommunity).</p>\n<p>This choreography of hands and fingers — a choreography that annexes photographs, books, and other objects set in motion — operates beyond the boundaries of the relational frame. It is thus a performative situation in its purest form. This understanding of the gesture enters into a highly peculiar interaction with the photographic image, drawing nearer to the interpretation proposed by Giorgio Agamben, who wrote: “What characterizes gesture is that in it nothing is being produced or acted, but rather something is being endured and supported. The gesture, in other words, opens the sphere of ethos as the more proper sphere of that which is human.”<a href=\"#sdfootnote6sym\" name=\"sdfootnote6anc\"><sup>6</sup></a> Agamben juxtaposes production and action, putting forth a definition of action that applies solely to the gesture: “if producing is a means in view of an end and praxis [action] is an end without means, the gesture then breaks with the false alternative between ends and means that paralyzes morality and presents instead means that, as such, evade the orbit of mediality without becoming, for this reason, ends. (…) If dance is gesture, it is so, rather, because it is nothing more than the endurance and the exhibition of the media character of corporal movements. The gesture is the exhibition of a mediality: it is the process of making a means visible as such.”<a href=\"#sdfootnote7sym\" name=\"sdfootnote7anc\"><sup>7</sup></a> In Agamben’s view, this understanding of the gesture is something that is potentially present in the image; something that wields a potentially liberating power, “because a certain kind of litigatio, a paralyzing power whose spell we need to break, is continuously at work in every image; it is as if a silent invocation calling for the liberation of the image into gesture arose from the entire history of art. This is what in ancient Greece was expressed by the legends in which statues break the ties holding them and begin to move.”<a href=\"#sdfootnote8sym\" name=\"sdfootnote8anc\"><sup>8</sup></a></p>\n<p>The images analyzed during the symposium with the help of discourse are thus accompanied by the pure mediality of the gesture. The performativity of the hands — which, in part, eludes classification – accompanies the translation of elements of the image into language. It would appear that the power of the conducted experiment is most strongly revealed here. It is as if the insurgent gestures did in fact set the images into motion; or, perhaps more likely, they captured that irreducible element of the image that cannot be articulated due to its formlessness, lack of attribution, and illogicalness, and belongs to the image, or image/gesture, itself. It is merely (and even) an action that is linked to the revelation of knowledge about the image, a movement within the frame of another (film) image, a pure mechanism with no end.</p>\n<p>The movement involved in the gesture — be it intentional or aimless — affects the images externally, as well. The materiality of the photographs placed on the table intensifies when acted upon by the hands: the pictures are cut, scattered, and colored. Reordered, replaced, and moved, they are constantly in a state of chaotic movement. This choreography of sorts to which the photographs are subjected makes them constantly ready for an encounter with other images (at which point the issues of materiality and immateriality begin to interpenetrate). The images literally bump into each other or are made to collide (as in the case of the session featuring Kuba Mikurda, who projected excerpts of Stanley Kubrick films onto pictures taken by Nicolas Grospierre); they multiply when several copies of the same image end up next to each other; they promise to produce surprising combinations that nevertheless remain highly ephemeral, disappearing with the next caprice of gesture; they are too fast for the eye. The ones that can be pinned down by our gaze are marked with a sense of loss: these include the photographs depicting Aneta Grzeszykowska and Jan Smaga, which stand in for their physical presence beyond the frame of the image.</p>\n<p>I would like at this point to devote more attention to the photographs by Paweł Bownik presented at the symposium. The juxtaposition of this artist’s work with the visual experiment conducted at the Zachęta Gallery allows us to make certain observations regarding the problem of performativity and documentation. I should start by noting that, in this article, performativity is understood as the eliciting of eventalization. However, this eventalization is not limited to that which is produced and received directly, or “live,” but also that which is mediated — in this case, through photographs and the film image.</p>\n<p></p>\n<p>We see the figure of a young man in a smart shirt standing in a corridor, his jacket leisurely slung across his shoulder, with his back turned to the camera. Two girls in checkered skirts lying on the floor in nearly symmetrical poses, surrounded by hardwood floorboards that obsessively repeat the checkered pattern. An elegant girl with her hair tossed to one side, strongly lit, gazing straight ahead. A boy in a modern, neon-colored outfit fidgets with his sock in the middle of an antique salon.</p>\n<p>Providing literal descriptions of the photographs comprising Paweł Bownik’s series “Colleagues” (exhibited and discussed at the Zachęta Gallery symposium) is a difficult and unrewarding task. The perfectly-executed works are displays of formal rigor, which is apparent in every element of the photograph and constitutes their real character. What makes this peculiar study of youth particularly disturbing is the disruption of the temporal order visible in the photo series. Each piece looks as if the photographed subject were from a different era; at the same time, there is something in each of the photos that compels us to briefly scour our memories in search of the original. The pose of the young man in the black-and-white photograph evokes associations with American noir films; the girls lying on the floor might be a reference to the images seen in Hitchcock movies; the portrait of the girl and that of the boy in the salon brings to mind familiar tricks: technical solutions typical of particular genres of painting. Ostentatiously artificial, these studio photographs produce the illusion of something that is ostensibly familiar.</p>\n<p>Paweł Bownik’s work approaches the subject of youth in a universal manner that is both beyond time and demonstratively anachronistic. The artist is uninterested in portraying young people realistically or considering the phenomenon of youth today. Instead, he examines the mechanism itself, rather than any of its specific realizations. At the same time, it seems obvious that all the temporal layers that emerge from his work are a kind of agitation within the present that is necessarily retromaniacal in nature.</p>\n<p>The photographs that make up the series “Colleagues” have a particular resonance with the performative format of the symposium itself. Bownik’s photos rely on a similar formula, one that requires the viewers to strongly engage their sight and grasp the formal structure within the images. Youth — ostensibly timeless and anachronistic — is perceived in terms of an elaborate theatrical performance. Bownik’s unsettling images become a sort of theater stage on which attempts are made to execute specific forms, conventions, and manners of depiction that mask the vague identity of the portrayed subjects. This staging, in which parts of the image constantly “resemble something,” can only be discerned once the viewer has discovered the exposing flaws, the idiosyncrasies that emphasize the compositional rigor.</p>\n<p>The gestures in Bownik’s photographs operate in a manner that brings to mind a process that almost resembles an investigation: following ambiguous clues, pointing out uncertain leads, tracing characteristic features, calling attention to the defects — all of which constitute the identity of the image. The leads emerge gradually: the abnormally elevated corridor floor on which the boy in the first photo stands, the oversized sweat stain on his shirt, the unconcealed set lighting, the conspicuous wall joints; the formal obsession guiding the checkered picture, the multiple structural rules within the image itself; the barely visible bead of sweat on the perfectly lit face of the girl, and, finally, the juxtaposition of the neon color palette in the boy’s outfit with the more traditional range visible on the walls of the salon. A certain distrust of the medium is required in order to follow all these leads: one must assume that nothing here has been left to chance. Bownik’s “operations within the scope of the model” can be viewed as a double staging. On the one hand, it is an elaborate, multi-faceted “performance of youth” that exhibits the associated mechanisms of attempts and subterfuge. At the same time, this performance is executed solely in the photograph and for its own sake.</p>\n<p>Bownik’s photographs can be included in the category of performed photography posited by Philip Auslander, who lists the artwork of Cindy Sherman, Marcel Duchamp, and Matthew Barney as examples of such images.<a href=\"#sdfootnote9sym\" name=\"sdfootnote9anc\"><sup>9</sup></a> What they have in common is that the photographed events or performances have been conjured solely for purposes of the image and have not been bestowed with any autonomous form of being.<a href=\"#sdfootnote10sym\" name=\"sdfootnote10anc\"><sup>10</sup></a> Photographs of this type constitute a special case: they are at once the performance itself and its own documentation. The staged events take place exclusively within the image: none of the situations photographed by Bownik “actually” happened. Each of them was painstakingly staged for the purposes of the photo shoot. Nevertheless, they often reveal clues that hint at earlier events, leads that document the reality of the staged tableaux.</p>\n<p>In his analysis of performance documentation, Auslander proposes an ostensibly dichotomous division into “documentary” and “theatrical” categories. The former mode involves simply recording an event that supposedly took place in the past. The latter includes the above-mentioned performance photography, used in reference to events that have been staged for the sole purpose of the photograph. The author of The Performativity of Performance Documentation posits that the difference between these two modes of documentation is ideological, rather than ontological, in nature. Meanwhile, a person who views an image interprets the performances — recorded and staged in the same manner — as an event.<a href=\"#sdfootnote11sym\" name=\"sdfootnote11anc\"><sup>11</sup></a> Auslander’s theses apply to photography and belong to a long-running discussion on the ephemeral nature not just of the performance, but performance art in general. However, it seems that the arguments cited above can be applied to a broader context and are relevant to the recording of any eventness and image (not just photographs).</p>\n<p>The recording of the performance/conversation held at the Zachęta symposium and the heavily staged photographs by Bownik appear to belong to two mutually exclusive modes: the documentary and the theatrical. Yet the juxtaposition of these two works casts doubt on a clear delineation between the two. The picture transmitted to the audience (and stored in the form of a recording) is more than just a recording of gestures and the movement of photographs: it is itself a performance. After all, it was only the act of recording — the encompassing event played out on the table among the hands and photographs — that turned this event into an actual performance, revealing the operative potential in the simultaneous movement of images and fingers and making it possible to perceive the regularity in this ephemeral event. It also revealed the future consequences of the connections established at the conversation/editing table, uncovering the tensions that existed between the material and the immaterial. It involved an event that, like the situations staged by Bownik, was essentially only seen by the “eyes” of the devices recording it. Viewers were cut off from the discussion going on at the table, and were instead immediately presented with its documentation and simultaneous dramatization. Furthermore, the recording of the conversation in which Bownik’s photographs were analyzed and set in motion displays a very high level of performative potential: it documents an event that is a performance in and of itself, one created with the help of staged photographs.</p>\n<p>The peculiar nature of the symposium at Zachęta was itself the result of another instance in which ossified categories were challenged: in this case, those of cognition and the senses. This event was more than just an experiment involving the production of knowledge, one carried out at the dynamic nexus of image and gesture; it was also something that might be described as a laboratory for the distribution and reception of knowledge. The situation devised therein (the audience facing away from the participants of the discussion, observing the discussion through its embodiment in gestures, knowledge being produced “before their very eyes”), was such that viewers rarely turned around to glance at the panelists: instead, they preferred to follow the movement of hands and images on the screen, looking away only sporadically. The very experience of observing a conversation in its purest form, rather than its participants, a conversation detached from any specific situation, resulted in yet another shift, this one taking place within the field of the visual. The dominant sense, sight, surrendered in a way to the sense of hearing, the ongoing discussions, and the voices of their participants. The performativity of the symposium lay in the establishment of such a scope of action that enabled the deconstruction of the assumed circumstances and facilitated a shift in this field.</p>\n<p>W.J.T. Mitchell argues that the term “visual media” is essentially a “colloquial expression used to designate things such as television, film, photography and painting, etc. But it is highly inexact and misleading. On closer inspection, all the so-called visual media turn out to involve the other senses (especially touch and hearing). All media are, from the standpoint of sensory modality, ‘mixed media’.”<a href=\"#sdfootnote12sym\" name=\"sdfootnote12anc\"><sup>12</sup></a> It appears that a similar situation was developed in this performative symposium. The atypically constructed visual material made it possible to draw the audience’s attention away from existing experiences and habits and redirect it toward hearing and the pleasure this movement entails.</p>\n<p>Ewelina Godlewska-Byliniak, a researcher who studies the phenomenon of the voice, points out that, “According to Barthes, the human voice is the privileged site of difference, differentiation, and deferral that eludes all knowledge, as it can never be exhausted by knowledge: there will always be some remainder, some appendix, something unspoken that is self-defined. That is, the voice. In psychoanalysis, the voice as such was elevated to the level of the object of desire, referred to as object (a).”<a href=\"#sdfootnote13sym\" name=\"sdfootnote13anc\"><sup>13</sup></a> The detachment of the image from the specific people producing speech and the accompanying spatial separation allows us to turn our attention to the voice itself, along with its irreducible surplus. This process, not unlike the selfless relationship between the gesture and attempts to explain the image in action, described previously in this article, facilitated the creation of an interesting web of cognitive processes during the symposium. The content created there was not authoritative in nature, as it operated in a performative structure that decentralized power centers and ostentatiously revealed the mechanisms that potentially lead to their formation, thus providing ample room for negotiation. By the same token, it enabled a homeostasis between individual media while respecting the difference inherent to each of them.</p>"}";s:8:"richtext";s:1:"1";s:8:"template";s:2:"17";s:9:"menuindex";s:1:"0";s:10:"searchable";s:1:"1";s:9:"cacheable";s:1:"1";s:9:"createdby";s:2:"13";s:9:"createdon";s:10:"1556213624";s:8:"editedby";s:2:"17";s:8:"editedon";s:10:"1602056470";s:7:"deleted";s:1:"0";s:9:"deletedon";s:1:"0";s:9:"deletedby";s:1:"0";s:11:"publishedon";s:10:"1556213624";s:11:"publishedby";s:2:"13";s:9:"menutitle";s:0:"";s:7:"donthit";s:1:"0";s:11:"haskeywords";s:1:"0";s:11:"hasmetatags";s:1:"0";s:10:"privateweb";s:1:"0";s:10:"privatemgr";s:1:"0";s:13:"content_dispo";s:1:"0";s:8:"hidemenu";s:1:"1";s:13:"alias_visible";s:1:"1";s:19:"issueArticleSummary";a:5:{i:0;s:19:"issueArticleSummary";i:1;s:188:"<p>The author criticaly analyses research and artistic seminar devoted to the question of the gesture with regards to the photographic image. She focuses on the works of Paweł Bownik.</p>";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"richtext";}s:16:"meta_description";a:5:{i:0;s:16:"meta_description";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"text";}s:15:"issueArticlePdf";a:5:{i:0;s:15:"issueArticlePdf";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"file";}s:19:"translationSelector";a:5:{i:0;s:19:"translationSelector";i:1;s:3:"859";i:2;s:0:"";i:3;s:0:"";i:4;s:18:"custom_tv:selector";}s:16:"issueArticleDate";a:5:{i:0;s:16:"issueArticleDate";i:1;s:0:"";i:2;s:8:"unixtime";i:3;s:0:"";i:4;s:4:"date";}s:17:"meta_custom_title";a:5:{i:0;s:17:"meta_custom_title";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"text";}s:13:"meta_img_fitv";a:5:{i:0;s:13:"meta_img_fitv";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:5:"image";}s:26:"issueArticleAuthorSelector";a:5:{i:0;s:26:"issueArticleAuthorSelector";i:1;s:3:"858";i:2;s:0:"";i:3;s:0:"";i:4;s:18:"custom_tv:selector";}s:24:"issueArticleBibliography";a:5:{i:0;s:24:"issueArticleBibliography";i:1;s:1114:"<p>Wołkoński, Sergiusz. <em>Człowiek wyrazisty. Sceniczne wychowanie gestu (według Delsarte’a)</em>. Translated by M. Szpakiewicz. Warszawa: Księgarnia I. Rzepeckiego, 1920.</p>
<p>Mościcki, Paweł. <em>Polityka teatru. Eseje o sztuce angażującej</em>. Warszawa: Wydawnictwo Krytyki Politycznej, 2008.</p>
<p>Hewitt, Andrew. <em>Social choreography: Ideology and Performance in Dance and Everyday Movement</em>. Durham and London: Duke University Press, 2005.</p>
<p>Agamben, Giorgio. “Uwagi o geście”. Translated by P. Mościcki. In <em>Agamben. Przewodnik Krytyki Politycznej</em>. Warszawa: Wydawnictwo Krytyki Politycznej, 2010.</p>
<p>Auslander, Philip. “The Performativity of Performance Documentation”. <em>PAJ: A Journal of Performance and Art</em> 3 (2006).</p>
<p>Mitchell, W.J.T. <em>There Are No Visual Media</em>. In <em>Sound</em>. Edited by C. Kelly. London-Cambridge, Mass.: Whitechapel Gallery, MIT Press, 2011.</p>
<p>Godlewska-Byliniak, Ewelina. <em>Teatr radio-logiczny Tymoteusza Karpowicza</em>. Warszawa: Wydawnictwa Uniwersytetu Warszawskiego, 2012.</p>
<p> </p>";i:2;s:0:"";i:3;s:28:"&w=100%&h=300px&edt=TinyMCE4";i:4;s:8:"richtext";}s:25:"issueArticleFootnotesText";a:5:{i:0;s:25:"issueArticleFootnotesText";i:1;s:2494:"<p><a href="#sdfootnote1anc" name="sdfootnote1sym">1</a>Sergey Volkonsky, Człowiek wyrazisty. Sceniczne wychowanie gestu (według Delsarte’a), trans. Mieczysław Szpakiewicz (Warsaw: Księgarnia I. Rzepeckiego, 1920), 70.</p>
<p><a href="#sdfootnote2anc" name="sdfootnote2sym">2</a>The participants of the symposium were: Rafał Milach, Anna Nałęcka, and Joanna Kinowska; Paweł Bownik and Weronika Szczawińska; Aneta Grzeszykowska, Jan Smaga, and Katarzyna Bojarska; Elżbieta Janicka, Wojciech Wilczyk, and Waldemar Baraniewski; Michał Kaczyński, Łukasz Gorczyca, and Paweł Szypulski; Kuba Mikurda and Nicolas Grospierre; and Krzysztof Pijarski.</p>
<p><a href="#sdfootnote3anc" name="sdfootnote3sym">3</a>From the announcement of the symposium. Quoted from <a href="https://zacheta.art.pl/en/kalendarz/sympozjum?setlang=1" target="_blank" rel="noopener">http://zacheta.art.pl/en/kalendarz/sympozjum?setlang=1</a>, accessed October 8, 2016.</p>
<p><a href="#sdfootnote4anc" name="sdfootnote4sym">4</a>Bertolt Brecht, Gestik, in: Paweł Mościcki, Polityka teatru. Eseje o sztuce angażującej (Warsaw: Wydawnictwo Krytyki Politycznej, 2008), 71.</p>
<p><a href="#sdfootnote5anc" name="sdfootnote5sym">5</a>Cf. Andrew Hewitt, Social choreography: Ideology and Performance in Dance and Everyday Movement (Durham and London: Duke University Press, 2005).</p>
<p><a href="#sdfootnote6anc" name="sdfootnote6sym">6</a>Giorgio Agamben, “Notes on Gesture” in Means Without End: Notes on Politics, trans. Vincenzo Binetti, Cesare Casarino (Minneapolis: University of Minnesota Press, 2000), 57.</p>
<p><a href="#sdfootnote7anc" name="sdfootnote7sym">7</a>Ibid., 58.</p>
<p><a href="#sdfootnote8anc" name="sdfootnote8sym">8</a>Ibid., 56.</p>
<p><a href="#sdfootnote9anc" name="sdfootnote9sym">9</a>Cf. Philip Auslander, “The Performativity of Performance Documentation,” PAJ: A Journal of Performance and Art 3 (2006), 2.</p>
<p><a href="#sdfootnote10anc" name="sdfootnote10sym">10</a>Ibid.</p>
<p><a href="#sdfootnote11anc" name="sdfootnote11sym">11</a>Ibid., 3–4.</p>
<p><a href="#sdfootnote12anc" name="sdfootnote12sym">12</a>W.J.T. Mitchell, “There Are No Visual Media,” in Sound, ed. Caleb Kelly (London–Massachusetts: Whitechapel Gallery, MIT Press, 2011), 76.</p>
<p><a href="#sdfootnote13anc" name="sdfootnote13sym">13</a>Ewelina Godlewska-Byliniak, Teatr radio-logiczny Tymoteusza Karpowicza (Warsaw: Wydawnictwa Uniwersytetu Warszawskiego, 2012), 32.</p>";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"richtext";}s:25:"issueArticleAuthorVariant";a:5:{i:0;s:25:"issueArticleAuthorVariant";i:1;s:3:"she";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"dropdown";}s:36:"issueArticleTranslationAuthorVariant";a:5:{i:0;s:36:"issueArticleTranslationAuthorVariant";i:1;s:2:"he";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"dropdown";}s:29:"issueArticleTranslationAuthor";a:5:{i:0;s:29:"issueArticleTranslationAuthor";i:1;s:12:"Arthur Barys";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"text";}s:20:"issueArticleKeywords";a:5:{i:0;s:20:"issueArticleKeywords";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"text";}s:15:"issueArticleDoi";a:5:{i:0;s:15:"issueArticleDoi";i:1;s:11:"2015.12.914";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"text";}s:11:"pdf_content";a:5:{i:0;s:11:"pdf_content";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"textarea";}s:15:"use_pdf_content";a:5:{i:0;s:15:"use_pdf_content";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:16:"custom_tv:switch";}s:21:"overwrite_pdf_content";a:5:{i:0;s:21:"overwrite_pdf_content";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:16:"custom_tv:switch";}s:33:"issueArticleTranslationAuthorLink";a:5:{i:0;s:33:"issueArticleTranslationAuthorLink";i:1;s:0:"";i:2;s:0:"";i:3;s:9:"&format=,";i:4;s:18:"custom_tv:selector";}s:13:"pdf_footnotes";a:5:{i:0;s:13:"pdf_footnotes";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:8:"textarea";}s:23:"overwrite_pdf_footnotes";a:5:{i:0;s:23:"overwrite_pdf_footnotes";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:16:"custom_tv:switch";}s:17:"use_pdf_footnotes";a:5:{i:0;s:17:"use_pdf_footnotes";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:16:"custom_tv:switch";}s:7:"pdfFile";a:5:{i:0;s:7:"pdfFile";i:1;s:52:"assets/files/article-pdf/issue-12/szczawinska-en.pdf";i:2;s:0:"";i:3;s:0:"";i:4;s:4:"file";}s:17:"__MODxSJScripts__";a:1:{i:1;s:120:"	<link rel="stylesheet" type="text/css" href="assets/templates/widok_tpl/minifyx/styles.min.4672983195df0c0237c3.css" />";}s:16:"__MODxJScripts__";a:2:{i:1;s:118:"	<script type="text/javascript" src="assets/templates/widok_tpl/minifyx/scripts.min.0e8961e12996bd7f5cde.js"></script>";i:2;s:170:"
	<script>
		$(document).ready(function () {
			$('a[href^="#"]').each(function(i,el){
				el.href = "[(site_url)][~[*id*]~]" + el.hash;
			});
		});
	</script>
	";}s:17:"__MODxDocGroups__";s:0:"";}<!--__MODxCacheSpliter__-->[!getPdf!]<!DOCTYPE html>
<html dir="ltr" lang="en-us">
	<head>
		<base href="https://www.pismowidok.org/">

		<meta charset="utf-8">
		
		<title>Images in Action. Photography, Gesture, Performativity | View. Theories and Practices of Visual Culture</title>

		<meta name="description" content="">
		<meta name="subject" content="company">
		<meta name="copyright" content="View. Theories and Practices of Visual Culture">
		<meta name="author" content="View. Theories and Practices of Visual Culture">
		<meta name="robots" content="index,follow">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="canonical" href="https://www.pismowidok.org/[~914~]">
		<link rel="alternate" href="https://www.pismowidok.org/" hreflang="pl">
		<link rel="alternate" href="https://www.pismowidok.org/en" hreflang="en">

		<!-- Schema.org markup for Google+ -->
		<meta itemprop="name" content="Images in Action. Photography, Gesture, Performativity | View. Theories and Practices of Visual Culture">
		<meta itemprop="description" content="">
		<meta itemprop="image" content="https://www.pismowidok.org/og-image-1200x630.jpg">

		<!-- Twitter Card -->
		<meta name="twitter:card" value="summary">
		<meta name="twitter:title" content="Images in Action. Photography, Gesture, Performativity | View. Theories and Practices of Visual Culture">
		<meta name="twitter:description" content="">
		<meta name="twitter:image:src" content="https://www.pismowidok.org/og-image-1200x630.jpg">

		<!-- Open Graph -->
		<meta property="og:url" content="https://www.pismowidok.org/[~914~]">
		<meta property="og:site_name" content="View. Theories and Practices of Visual Culture">
		<meta property="og:title" content="Images in Action. Photography, Gesture, Performativity | View. Theories and Practices of Visual Culture">
		<meta property="og:description" content="">
		<meta property="og:image" content="https://www.pismowidok.org/og-image-1200x630.jpg">
		<meta property="og:image:type" content="image/jpeg">
		<meta property="og:image:width" content="1200">
		<meta property="og:image:height" content="630">
		
		<!-- Favicon -->
		<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
		<link rel="manifest" href="site.webmanifest">
		<link rel="mask-icon" href="safari-pinned-tab.svg" color="#5bbad5">
		<meta name="apple-mobile-web-app-title" content="Widok">
		<meta name="application-name" content="Widok">
		<meta name="msapplication-TileColor" content="#2b5797">
		<meta name="theme-color" content="#ffffff">
		
		
		<style>
	
  body.tpl-17 #header,
  body.tpl-43 #header,
  body.tpl-40.has-docked-header #header,
  body.tpl-40 .c-headerissue__number,
	.c-jump2issue__circle,
	.m-page-content--slides .owl-theme .owl-dots .owl-dot.active span, 
	.m-page-content--slides .owl-theme .owl-dots .owl-dot:hover span,
	.m-presentation--bgc-issue,
	.m-presentation--big-text,
	.m-presentation--slides .owl-dots .owl-dot.active span, 
	.m-presentation--slides .owl-dots .owl-dot:hover span, 
	.m-presentation--slides-alt .owl-dots .owl-dot.active span, 
	.m-presentation--slides-alt .owl-dots .owl-dot:hover span,
	.u-typo ul li::before {
    background-color: #c69 !important;
  }
  body.tpl-40 .c-headerissue__number {
    color: #000 !important;
  }
  body.tpl-40.has-docked-header .c-headerissue__number {
    color: #fff !important;
  }
  body.tpl-40.has-docked-header .c-headerissue__number {
		background-color: #000 !important;
  }
	
	.c-headerissue__number {
		color: #fff !important;
		background-color: #000 !important;
	}
	
	body.has-bgc-black .c-headerissue__number {
		color: #000 !important;
		background-color: #fff !important;
	}
	
	[data-toggle="popover"],
	.c-archive-year,
	.c-article-audio__caption, 
	.c-article-audio__caption *, 
	.c-article-slides__caption, 
	.c-article-slides__caption *,
	.c-article-title a,
	.c-article-video__caption, 
	.c-article-video__caption *,
	.c-article-meta__author,
	.c-article-meta__author a,
	.c-article-video__caption,
	.c-article-video__caption *,
	.c-issue-toc__section-title,
	.c-issue-toc__article:before,
	.c-issue-toc__article-authors,
	.c-issue-toc__article--has-translation .c-issue-toc__article-authors a,
	.c-issue-toc__article-collapse-inner a,
	.u-typo figcaption,
	.u-typo figcaption *,
	.u-typo a,
	.u-typo a:hover,
	.u-typo h3,
	.u-typo h4,
	.c-footnotes__item,
	.c-sitenav__search,
	.m-presentation--image-text .u-typo,
	.m-presentation--full-image figcaption,
  .sl-wrapper .sl-close,
  .sl-wrapper .sl-image .sl-caption,
  .sl-wrapper .sl-navigation button,
	.m-article .u-typo h2,
	.m-bibliography__content,
	.m-footnotes p {
		color: #c69 !important;
	}
	
	.m-presentation--bgc-white .m-presentation__caption,
	.m-presentation--bgc-white .m-presentation__caption *,
	.presentation-num.bgc--white {
		/* color: #c69 !important; */
	}
	.m-presentation--bgc-white .m-presentation__caption a:hover,
	.m-presentation--bgc-issue .m-presentation__caption a:hover {
		color: #000 !important;
	}
	
	.c-archive-year span {
		border-color: #c69 !important;
	}
	
	.m-presentation--bgc-issue.m-presentation--image-text,
	.m-presentation--bgc-issue.m-presentation--image-text .u-typo,
	.m-presentation--bgc-issue .m-presentation__caption,
	.m-presentation--bgc-issue .m-presentation__caption *,
	.m-presentation--bgc-issue .c-article-meta__author,
	.m-presentation--bgc-issue .c-article-meta__author a {
		/* color: #000 !important; */
	}
	
	.c-sitenav__search svg circle, 
	.c-sitenav__search svg line {
		stroke: #c69 !important;
	}
	
	.m-presentation__control--mute .speaker-icon path {
    fill: #c69 !important;
	}
	.m-presentation__control--mute.is-inverse .speaker-icon path {
    fill: #000 !important;
	}
	
	.m-presentation__caption-btn-collapse::after {
		border-top-color: #c69 !important;
	}
	.m-presentation__caption-btn-collapse[aria-expanded="true"]::after {
		border-top-color: transparent !important;
		border-bottom-color: #c69 !important;
	}
	.m-presentation--bgc-issue .m-presentation__caption-btn-collapse::after {
		border-top-color: #000 !important;
	}
	.m-presentation--bgc-issue .m-presentation__caption-btn-collapse[aria-expanded="true"]::after {
		border-top-color: transparent !important;
		border-bottom-color: #000 !important;
	}
	
		.m-presentation--bgc-issue .m-presentation__caption {
			/* background-color:rgba(204,102,153,0.8) !important; */
			/* background-color:#c69 !important; */
		}
		  .presentation-num.bgc--issue {
		  	/* background-color:rgba(204,102,153,0.8) !important;
		  					color:#000 !important; */
		  }
	
	.m-presentation--bgc-issue .m-presentation__caption .collapse-inner * {
    
  }
	
	.m-presentation__modal-open i, .m-presentation__modal-open:hover i, .presentation-modal .close i, .presentation-modal .close:hover i {
		/* color:#c69 !important; */
	}
	
	.m-presentation--bgc-issue .m-presentation__modal-open {
		/* background-color:rgba(204,102,153,0.8) !important; */
	}
	.m-presentation--bgc-black 	.m-presentation__caption,
	.m-presentation--bgc-black 	.m-presentation__caption *,
	.m-presentation--bgc-black 	.m-presentation__caption a:hover{
		/* color: #fff !important; */
		color: #000 !important;
	}
	
	.presentation-modal .modal-body, .presentation-modal .modal-title {
		/* color:#c69; */
	}
	.modal-issue-open .presentation-modal .modal-body, .modal-issue-open .presentation-modal .modal-title {
		/* color:#000; */
	}
	
	body.modal-issue-open .modal-backdrop {
		/* background-color:rgba(204,102,153,0.8) !important; */
	}
	body.modal-issue-open .presentation-modal a.close {
			/* background-color:rgba(204,102,153,0.8) !important; */
		}
	
	.green-audio-player,
	.green-audio-player .controls {
		color:#c69 !important;
	}
	
	.green-audio-player .controls .controls__slider::before, .green-audio-player .controls .controls__slider::after,
	.green-audio-player .slider,
	.green-audio-player .slider .gap-progress .pin,
	.green-audio-player .slider .gap-progress {
		background:#c69 !important;
	}
	
	.green-audio-player svg circle, .green-audio-player svg polygon, .green-audio-player svg line {
		stroke:#c69 !important;
	}
	
</style>
		
		
		<style>
			.m-article .u-typo p {
				/*rag-adjust: small-words;*/
				/*widow-adjust: non-breaking-space;*/
			}
		</style>
		
		
		
		
	</head>
	<body class="context-en tpl-17 page-id-914 parent-id-908">
		
    
    <div id="preloader" aria-hidden="true"></div>
		<span id="js-selected-issue" data-selected-issue-id="906" data-selected-issue-color="#c69" aria-hidden="true"></span>

		<header id="header">
     
      <div class="c-navbar">
        <a class="c-sitelogo" href="https://www.pismowidok.org/en">
          <span class="c-sitelogo__icon"><img src="assets/templates/widok_tpl/img/logo.svg" alt="View. Theories and Practices of Visual Culture"></span>
          <span class="c-sitelogo__full u-underline-border">View. Theories and Practices of Visual Culture</span>
        </a>
        <div class="c-headertools">
          <ul>
            <li class="c-headertools__lang">
							<a class="c-headertools__lang-link u-underline-border" href="/pl/archiwum/2015/12-fotografia-i-skutecznosc-gestu/obrazy-w-akcji"><span>PL</span></a>
							<!-- <a class="c-headertools__lang-link u-underline-border" href="[~859~]"><span>PL</span></a> -->
            </li>
            <li class="c-headertools__nav">
              <button type="button" class="c-headertools__nav-button js-toggle-nav">
                <span></span>
              </button>
            </li>
            <li class="c-headertools__search">
              <a href="[~39~]">
                <svg class="c-headertools__search-icon" version="1.0"
                     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
                     x="0px" y="0px" width="28px" height="28px" viewBox="-0.399 -0.399 28 28"
                     overflow="visible" enable-background="new -0.399 -0.399 28 28" xml:space="preserve">
                  <defs>
                  </defs>
                  <g>
                    <circle fill="none" stroke="#000000" stroke-width="2" cx="12" cy="12" r="11"/>
                    <line fill="none" stroke="#000000" stroke-width="2" x1="20.467" y1="20.467" x2="26.496" y2="26.495"/>
                  </g>
                </svg>
              </a>
            </li>
          </ul>
        </div>
        <div class="c-headerissue">
          <span class="c-headerissue__title">No.</span>
					[!headerCircleHtml!]
        </div>
      </div>
      
      <nav class="c-sitenav">
        <div class="c-sitenav__main">
          <ul>
            <li class="c-sitenav__search">
              <svg version="1.0"
                   xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
                   x="0px" y="0px" width="28px" height="28px" viewBox="-0.399 -0.399 28 28"
                   overflow="visible" enable-background="new -0.399 -0.399 28 28" xml:space="preserve">
                <defs>
                </defs>
                <g>
                  <circle fill="none" stroke="#000000" stroke-width="2" cx="12" cy="12" r="11"/>
                  <line fill="none" stroke="#000000" stroke-width="2" x1="20.467" y1="20.467" x2="26.496" y2="26.495"/>
                </g>
              </svg>
              <a href="[~39~]">Wyszukaj</a>
            </li>
            <li>
	<a href="/en/about" title="About" ><span>About</span></a>
</li>
<li>
	<a href="/en/foundation" title="Foundation" ><span>Foundation</span></a>
</li>
<li class="active">
	<a href="/en/archive" title="Archive" ><span>Archive</span></a>
</li>
<li class="last">
	<a href="/en/cfp" title="CFP" ><span>CFP</span></a>
</li>

          </ul>
        </div>
      </nav>
      
    </header>
    
    <main id="main">
			



	<a class="c-download c-download--article-desktop" target="_blank" href="assets/files/article-pdf/issue-12/szczawinska-en.pdf"></a>
	

<div class="container-fluid">
	<div class="content-canvas content-canvas--small">
		<div class="content-canvas__inner">
			<article class="m-article">

				<header class="m-article__header">
					<h1 class="c-article-title c-article-title--has-download">
						<span>Images in Action. Photography, Gesture, Performativity</span>
						
						
						<a class="c-download c-download--article-mobile" target="_blank" href="assets/files/article-pdf/issue-12/szczawinska-en.pdf"></a>
						
						
					</h1>
					<div class="c-article-meta">
	
	
	<p class="c-article-meta__author">
		Author: 
		<a href="/en/bio?id=858">Weronika Szczawińska</a>
	</p>
	
	
	
	<p class="c-article-meta__author">
		Translated by: 
		
		Arthur Barys
		
	</p>
	
	
</div>
				</header>

				<section class="u-typo">   <p>We ought to start by examining the hands. “How astonishing it is that&nbsp;the hand can express so much! Yet what is more astonishing is that&nbsp;the hand embodies so little. Just look at our hands: what unhewn, bulky, lazy blocks they are. What unprocessed material they are, always identical and always similar to each other, with&nbsp;no play or internal life,”<a href="#sdfootnote1sym" name="sdfootnote1anc"><sup>1</sup></a> remarked Prince Sergey Volkonsky in his 19th century description of the stage methods developed by François Delsarte, creator of a&nbsp;codified system of acting techniques. Volkonsky devotes his subsequent reflections to the means by which this&nbsp;unruly “cluster” of the hand not only acquires the necessary expressive power, but, perhaps more importantly, is unleashed from&nbsp;this state of meaningless raw material and (through the proper formatting) begins to communicate very specific meanings, here ascribed to illustrations that&nbsp;demonstrate the appropriate modeling of the gesture. It is worth noting that&nbsp;most of the world’s theatrical systems contain a&nbsp;tradition of disciplined approach to the hands: they are subjected to codified exercises and acquire the ability to speak through&nbsp;the study of a&nbsp;formal language. Traces of this&nbsp;can likely be found in the popular saying regarding&nbsp;bad actors who “don’t even know what to do with&nbsp;their hands on stage.” This&nbsp;is an important clue: it seems that&nbsp;a&nbsp;hand that&nbsp;is devoid of form when viewed in public threatens the existing order and remains ready to engage in subversive activity.</p> <p>It is precisely hands that&nbsp;became the main — or at least the most spectacular — actors in the performative symposium “Gesture Toward&nbsp;Photography,” held by Krzysztof Pijarski at the Zachęta Gallery in Warsaw in October 2013.<a href="#sdfootnote2sym" name="sdfootnote2anc"><sup>2</sup></a> Comprising six intensive sessions, the two-day event became a&nbsp;peculiar experiment designed to test an alternative model for&nbsp;producing knowledge (with a&nbsp;particular focus, of course, on the knowledge both generated by — and created for&nbsp;— the photographic image). The accompanying program explains that&nbsp;“In place of a&nbsp;situation where the speaker, separated from&nbsp;the audience, shares his already prepared knowledge, the performative symposium proposes a&nbsp;meeting of several people — artists and theorists — to discuss specific photographs in any format, books or contact sheets, in order to ‘discover’ or explore them — for&nbsp;each other and for&nbsp;the gathered audience. The process of discovering/exploring the images will be carried out not only through&nbsp;a&nbsp;discussion, but&nbsp;essentially, via&nbsp;the exchange of gestures: by pointing a&nbsp;finger, juxtaposing, cropping, inscribing, outlining, etc. — the whole repertoire of responses to the images which the body has at its disposal.”<a href="#sdfootnote3sym" name="sdfootnote3anc"><sup>3</sup></a> In effect, the symposium became more than&nbsp;just an interesting subversion of the existing conference standard: it resulted in several meaningful shifts involving the categories of gesture and visuality itself. It is precisely this&nbsp;shift that&nbsp;I&nbsp;wish to explore in the commentary below.</p> <p>Held in an empty white room, the symposium immediately revealed its theatrical potential; or, rather, it ostentatiously established a&nbsp;performative frame for&nbsp;the events. The participants of the discussion, meaning teams that&nbsp;invariably included Krzysztof Pijarski, artists working in the medium of photography, and an interlocutor, sat at a&nbsp;round wooden table, while the audience took their seats with&nbsp;their backs to the group, viewing the discussion on a&nbsp;screen linked to a&nbsp;camera placed over&nbsp;the table. The audience heard the participants while also observing their hands, which performed a&nbsp;variety of operations on the discussed images placed before&nbsp;them. Each conversation held at the symposium was presented to the audience in this&nbsp;manner and recorded as a&nbsp;film. I&nbsp;would like&nbsp;to examine several themes that&nbsp;emerged from&nbsp;the encounters as held in this&nbsp;format: namely the relationship between&nbsp;the image and gesture that&nbsp;formed during&nbsp;the filming of the event, the peculiarly-planned circumstances for&nbsp;the distribution of knowledge, and the photographic work of Paweł Bownik, whom I&nbsp;accompanied as an interlocutor on one panel.</p> <p>The characteristic feature of the hands depicted in the symposium recordings are their vitality and their readiness for&nbsp;incessant action. Very rarely do they rest motionlessly; even then they clearly reveal the impulses that&nbsp;will momentarily result in further movement. Though the individual films depicting each conversation differ in terms of their dynamics, viewing them in their entirety allows one to compile a&nbsp;catalog of recurring gestures. The catalogue could include, more or less, the following: the touching of visual materials; smoothing them, holding, moving, arranging or scattering them; gestures also associated with&nbsp;the act of delivering or explaining one’s thoughts to someone (in various manners: typically with&nbsp;the palms facing inwards or upwards), responding to another person’s thoughts or words, with&nbsp;the hands moving in and out of the picture; and finally, ostentatiously theatrical hands, self-conscious of being filmed (e.g., the hands sliding underneath&nbsp;a&nbsp;convex photograph in the panel devoted to the work of Grospierre).</p> <p>The dynamics of these gestures, as depicted in the recordings of the hands, can be examined from&nbsp;the perspective of the Brechtian concept of the Gestus, that&nbsp;is, the “complex of gestures and expressions that&nbsp;form the basis of various actions among&nbsp;people, and the behavior common to all involved in these actions (…) or the complex of gestures and expressions that, when performed by a&nbsp;person, elicit specific behavior in others, or, finally, the demeanor of an individual person. (…) Gestus always denotes the attitude people have toward&nbsp;each other.”<a href="#sdfootnote4sym" name="sdfootnote4anc"><sup>4</sup></a> It is thus a&nbsp;dynamic web of interactions that&nbsp;provides insight into&nbsp;social relations, or at least into&nbsp;the dynamic of relations that&nbsp;emerges among&nbsp;a&nbsp;group of people.</p> <p>The physical gestures performed as a&nbsp;part of the Gestuses operating within&nbsp;the recordings are often linked to a&nbsp;very specific action in relation to the photographic images. For&nbsp;example, participants of the various panels cut the photographs and arrange them in space (Grospierre), draw on them using markers (Bownik), and point out particular elements in them (Wilczyk and Janicka). The conversation of hands observed on the screen somehow elucidates, explains, or “unpacks” the artworks placed on the table (gradual and methodical “unpacking” being the main discursive strategy of the symposium); by performing intuitively comprehensible gestures, the hands weave a&nbsp;clear web of communication.</p> <p>The image presented in this&nbsp;manner is utterly incomplete. What made the recordings screened at the Zachęta Gallery unique, and facilitated a&nbsp;shift in the field of knowledge and visuality, was the result achieved within&nbsp;the assumed framework of the experiment and — in keeping with&nbsp;its logic — one achieved only in practice. This&nbsp;is because the aforementioned clear gestures were accompanied by completely unclassifiable conversations that&nbsp;comprised a&nbsp;peculiar form of anti-iconography. The recorded discussions in fact reveal a&nbsp;“gestural surplus,” this&nbsp;unnameable feverish activity of the hands. Moreover, these gestures usually contradict the words accompanying them in the conversation: the former are completely inadequate to the latter. The image of the gestural conversation is thus replete with&nbsp;images of fingertips being picked at, hands being rubbed, clumsy, aimless movements, crossed fingers, and reflexive tapping. The actions of the hands — irrespective of the situation, words, and gestures — have no direct relation to anything else and cannot be confined to the above-mentioned concept of the Gestus. The gestures performed by the mutinous hands are more easily described using the concept of social choreography,<a href="#sdfootnote5sym" name="sdfootnote5anc"><sup>5</sup></a> which seems much broader and encompasses the entirety of movement connections within&nbsp;a&nbsp;community (or, in this&nbsp;case, a&nbsp;microcommunity).</p> <p>This choreography of hands and fingers — a&nbsp;choreography that&nbsp;annexes photographs, books, and other objects set in motion — operates beyond&nbsp;the boundaries of the relational frame. It is thus a&nbsp;performative situation in its purest form. This&nbsp;understanding of the gesture enters into&nbsp;a&nbsp;highly peculiar interaction with&nbsp;the photographic image, drawing nearer to the interpretation proposed by Giorgio Agamben, who wrote: “What characterizes gesture is that&nbsp;in it nothing is being produced or acted, but&nbsp;rather something is being endured and supported. The gesture, in other words, opens the sphere of ethos as the more proper sphere of that&nbsp;which is human.”<a href="#sdfootnote6sym" name="sdfootnote6anc"><sup>6</sup></a> Agamben juxtaposes production and action, putting forth a&nbsp;definition of action that&nbsp;applies solely to the gesture: “if producing is a&nbsp;means in view of an end and praxis [action] is an end without&nbsp;means, the gesture then breaks with&nbsp;the false alternative between&nbsp;ends and means that&nbsp;paralyzes morality and presents instead means that, as such, evade the orbit of mediality without&nbsp;becoming, for&nbsp;this reason, ends. (…) If dance is gesture, it is so, rather, because it is nothing more than&nbsp;the endurance and the exhibition of the media character of corporal movements. The gesture is the exhibition of a&nbsp;mediality: it is the process of making a&nbsp;means visible as such.”<a href="#sdfootnote7sym" name="sdfootnote7anc"><sup>7</sup></a> In Agamben’s view, this&nbsp;understanding of the gesture is something that&nbsp;is potentially present in the image; something that&nbsp;wields a&nbsp;potentially liberating power, “because a&nbsp;certain kind of litigatio, a&nbsp;paralyzing power whose spell we need to break, is continuously at work in every image; it is as if a&nbsp;silent invocation calling for&nbsp;the liberation of the image into&nbsp;gesture arose from&nbsp;the entire history of art. This&nbsp;is what in ancient Greece was expressed by the legends in which statues break the ties holding them and begin to move.”<a href="#sdfootnote8sym" name="sdfootnote8anc"><sup>8</sup></a></p> <p>The images analyzed during&nbsp;the symposium with&nbsp;the help of discourse are thus accompanied by the pure mediality of the gesture. The performativity of the hands — which, in part, eludes classification –&nbsp;accompanies the translation of elements of the image into&nbsp;language. It would appear that&nbsp;the power of the conducted experiment is most strongly revealed here. It is as if the insurgent gestures did in fact set the images into&nbsp;motion; or, perhaps more likely, they captured that&nbsp;irreducible element of the image that&nbsp;cannot be articulated due to its formlessness, lack of attribution, and illogicalness, and belongs to the image, or image/gesture, itself. It is merely (and even) an action that&nbsp;is linked to the revelation of knowledge about&nbsp;the image, a&nbsp;movement within&nbsp;the frame of another (film) image, a&nbsp;pure mechanism with&nbsp;no end.</p> <p>The movement involved in the gesture — be it intentional or aimless — affects the images externally, as well. The materiality of the photographs placed on the table intensifies when acted upon&nbsp;by the hands: the pictures are cut, scattered, and colored. Reordered, replaced, and moved, they are constantly in a&nbsp;state of chaotic movement. This&nbsp;choreography of sorts to which the photographs are subjected makes them constantly ready for&nbsp;an encounter with&nbsp;other images (at which point the issues of materiality and immateriality begin to interpenetrate). The images literally bump into&nbsp;each other or are made to collide (as in the case of the session featuring Kuba Mikurda, who projected excerpts of Stanley Kubrick films onto&nbsp;pictures taken by Nicolas Grospierre); they multiply when several copies of the same image end up next to each other; they promise to produce surprising combinations that&nbsp;nevertheless remain highly ephemeral, disappearing with&nbsp;the next caprice of gesture; they are too fast for&nbsp;the eye. The ones that&nbsp;can be pinned down&nbsp;by our gaze are marked with&nbsp;a&nbsp;sense of loss: these include the photographs depicting Aneta Grzeszykowska and Jan Smaga, which stand in for&nbsp;their physical presence beyond&nbsp;the frame of the image.</p> <p>I would like&nbsp;at this&nbsp;point to devote more attention to the photographs by Paweł Bownik presented at the symposium. The juxtaposition of this&nbsp;artist’s work with&nbsp;the visual experiment conducted at the Zachęta Gallery allows us to make certain observations regarding&nbsp;the problem of performativity and documentation. I&nbsp;should start by noting that, in this&nbsp;article, performativity is understood as the eliciting of eventalization. However, this&nbsp;eventalization is not limited to that&nbsp;which is produced and received directly, or “live,” but&nbsp;also that&nbsp;which is mediated — in this&nbsp;case, through&nbsp;photographs and the film image.</p> <p></p> <p>We see the figure of a&nbsp;young man in a&nbsp;smart shirt standing in a&nbsp;corridor, his jacket leisurely slung across&nbsp;his shoulder, with&nbsp;his back turned to the camera. Two girls in checkered skirts lying on the floor in nearly symmetrical poses, surrounded by hardwood floorboards that&nbsp;obsessively repeat the checkered pattern. An elegant girl with&nbsp;her hair tossed to one side, strongly lit, gazing straight ahead. A&nbsp;boy in a&nbsp;modern, neon-colored outfit fidgets with&nbsp;his sock in the middle of an antique salon.</p> <p>Providing literal descriptions of the photographs comprising Paweł Bownik’s series “Colleagues” (exhibited and discussed at the Zachęta Gallery symposium) is a&nbsp;difficult and unrewarding task. The perfectly-executed works are displays of formal rigor, which is apparent in every element of the photograph and constitutes their real character. What makes this&nbsp;peculiar study of youth particularly disturbing is the disruption of the temporal order visible in the photo series. Each piece looks as if the photographed subject were from&nbsp;a&nbsp;different era; at the same time, there is something in each of the photos that&nbsp;compels us to briefly scour our memories in search of the original. The pose of the young man in the black-and-white photograph evokes associations with&nbsp;American noir films; the girls lying on the floor might be a&nbsp;reference to the images seen in Hitchcock movies; the portrait of the girl and that&nbsp;of the boy in the salon brings to mind familiar tricks: technical solutions typical of particular genres of painting. Ostentatiously artificial, these studio photographs produce the illusion of something that&nbsp;is ostensibly familiar.</p> <p>Paweł Bownik’s work approaches the subject of youth in a&nbsp;universal manner that&nbsp;is both beyond&nbsp;time and demonstratively anachronistic. The artist is uninterested in portraying young people realistically or considering&nbsp;the phenomenon of youth today. Instead, he examines the mechanism itself, rather than&nbsp;any of its specific realizations. At the same time, it seems obvious that&nbsp;all the temporal layers that&nbsp;emerge from&nbsp;his work are a&nbsp;kind of agitation within&nbsp;the present that&nbsp;is necessarily retromaniacal in nature.</p> <p>The photographs that&nbsp;make up the series “Colleagues” have a&nbsp;particular resonance with&nbsp;the performative format of the symposium itself. Bownik’s photos rely on a&nbsp;similar formula, one that&nbsp;requires the viewers to strongly engage their sight and grasp the formal structure within&nbsp;the images. Youth — ostensibly timeless and anachronistic — is perceived in terms of an elaborate theatrical performance. Bownik’s unsettling images become a&nbsp;sort of theater stage on which attempts are made to execute specific forms, conventions, and manners of depiction that&nbsp;mask the vague identity of the portrayed subjects. This&nbsp;staging, in which parts of the image constantly “resemble something,” can only be discerned once the viewer has discovered the exposing flaws, the idiosyncrasies that&nbsp;emphasize the compositional rigor.</p> <p>The gestures in Bownik’s photographs operate in a&nbsp;manner that&nbsp;brings to mind a&nbsp;process that&nbsp;almost resembles an investigation: following&nbsp;ambiguous clues, pointing out uncertain leads, tracing characteristic features, calling attention to the defects — all of which constitute the identity of the image. The leads emerge gradually: the abnormally elevated corridor floor on which the boy in the first photo stands, the oversized sweat stain on his shirt, the unconcealed set lighting, the conspicuous wall joints; the formal obsession guiding the checkered picture, the multiple structural rules within&nbsp;the image itself; the barely visible bead of sweat on the perfectly lit face of the girl, and, finally, the juxtaposition of the neon color palette in the boy’s outfit with&nbsp;the more traditional range visible on the walls of the salon. A&nbsp;certain distrust of the medium is required in order to follow all these leads: one must assume that&nbsp;nothing here has been left to chance. Bownik’s “operations within&nbsp;the scope of the model” can be viewed as a&nbsp;double staging. On the one hand, it is an elaborate, multi-faceted “performance of youth” that&nbsp;exhibits the associated mechanisms of attempts and subterfuge. At the same time, this&nbsp;performance is executed solely in the photograph and for&nbsp;its own sake.</p> <p>Bownik’s photographs can be included in the category of performed photography posited by Philip Auslander, who lists the artwork of Cindy Sherman, Marcel Duchamp, and Matthew Barney as examples of such images.<a href="#sdfootnote9sym" name="sdfootnote9anc"><sup>9</sup></a> What they have in common is that&nbsp;the photographed events or performances have been conjured solely for&nbsp;purposes of the image and have not been bestowed with&nbsp;any autonomous form of being.<a href="#sdfootnote10sym" name="sdfootnote10anc"><sup>10</sup></a> Photographs of this&nbsp;type constitute a&nbsp;special case: they are at once the performance itself and its own documentation. The staged events take place exclusively within&nbsp;the image: none of the situations photographed by Bownik “actually” happened. Each of them was painstakingly staged for&nbsp;the purposes of the photo shoot. Nevertheless, they often reveal clues that&nbsp;hint at earlier events, leads that&nbsp;document the reality of the staged tableaux.</p> <p>In his analysis of performance documentation, Auslander proposes an ostensibly dichotomous division into&nbsp;“documentary” and “theatrical” categories. The former mode involves simply recording an event that&nbsp;supposedly took place in the past. The latter includes the above-mentioned performance photography, used in reference to events that&nbsp;have been staged for&nbsp;the sole purpose of the photograph. The author of The Performativity of Performance Documentation posits that&nbsp;the difference between&nbsp;these two modes of documentation is ideological, rather than&nbsp;ontological, in nature. Meanwhile, a&nbsp;person who views an image interprets the performances — recorded and staged in the same manner — as an event.<a href="#sdfootnote11sym" name="sdfootnote11anc"><sup>11</sup></a> Auslander’s theses apply to photography and belong to a&nbsp;long-running discussion on the ephemeral nature not just of the performance, but&nbsp;performance art in general. However, it seems that&nbsp;the arguments cited above&nbsp;can be applied to a&nbsp;broader context and are relevant to the recording of any eventness and image (not just photographs).</p> <p>The recording of the performance/conversation held at the Zachęta symposium and the heavily staged photographs by Bownik appear to belong to two mutually exclusive modes: the documentary and the theatrical. Yet the juxtaposition of these two works casts doubt on a&nbsp;clear delineation between&nbsp;the two. The picture transmitted to the audience (and stored in the form of a&nbsp;recording) is more than&nbsp;just a&nbsp;recording of gestures and the movement of photographs: it is itself a&nbsp;performance. After&nbsp;all, it was only the act of recording — the encompassing event played out on the table among&nbsp;the hands and photographs — that&nbsp;turned this&nbsp;event into&nbsp;an actual performance, revealing the operative potential in the simultaneous movement of images and fingers and making it possible to perceive the regularity in this&nbsp;ephemeral event. It also revealed the future consequences of the connections established at the conversation/editing table, uncovering the tensions that&nbsp;existed between&nbsp;the material and the immaterial. It involved an event that, like&nbsp;the situations staged by Bownik, was essentially only seen by the “eyes” of the devices recording it. Viewers were cut off&nbsp;from the discussion going on at the table, and were instead immediately presented with&nbsp;its documentation and simultaneous dramatization. Furthermore, the recording of the conversation in which Bownik’s photographs were analyzed and set in motion displays a&nbsp;very high level of performative potential: it documents an event that&nbsp;is a&nbsp;performance in and of itself, one created with&nbsp;the help of staged photographs.</p> <p>The peculiar nature of the symposium at Zachęta was itself the result of another instance in which ossified categories were challenged: in this&nbsp;case, those of cognition and the senses. This&nbsp;event was more than&nbsp;just an experiment involving the production of knowledge, one carried out at the dynamic nexus of image and gesture; it was also something that&nbsp;might be described as a&nbsp;laboratory for&nbsp;the distribution and reception of knowledge. The situation devised therein (the audience facing away from&nbsp;the participants of the discussion, observing the discussion through&nbsp;its embodiment in gestures, knowledge being produced “before their very eyes”), was such that&nbsp;viewers rarely turned around&nbsp;to glance at the panelists: instead, they preferred to follow the movement of hands and images on the screen, looking away only sporadically. The very experience of observing a&nbsp;conversation in its purest form, rather than&nbsp;its participants, a&nbsp;conversation detached from&nbsp;any specific situation, resulted in yet another shift, this&nbsp;one taking place within&nbsp;the field of the visual. The dominant sense, sight, surrendered in a&nbsp;way to the sense of hearing, the ongoing discussions, and the voices of their participants. The performativity of the symposium lay in the establishment of such a&nbsp;scope of action that&nbsp;enabled the deconstruction of the assumed circumstances and facilitated a&nbsp;shift in this&nbsp;field.</p> <p>W.J.T. Mitchell argues that&nbsp;the term “visual media” is essentially a&nbsp;“colloquial expression used to designate things such as television, film, photography and painting, etc. But&nbsp;it is highly inexact and misleading. On closer inspection, all the so-called visual media turn out to involve the other senses (especially touch and hearing). All media are, from&nbsp;the standpoint of sensory modality, ‘mixed media’.”<a href="#sdfootnote12sym" name="sdfootnote12anc"><sup>12</sup></a> It appears that&nbsp;a&nbsp;similar situation was developed in this&nbsp;performative symposium. The atypically constructed visual material made it possible to draw the audience’s attention away from&nbsp;existing experiences and habits and redirect it toward&nbsp;hearing and the pleasure this&nbsp;movement entails.</p> <p>Ewelina Godlewska-Byliniak, a&nbsp;researcher who studies the phenomenon of the voice, points out that, “According to Barthes, the human voice is the privileged site of difference, differentiation, and deferral that&nbsp;eludes all knowledge, as it can never be exhausted by knowledge: there will always be some remainder, some appendix, something unspoken that&nbsp;is self-defined. That&nbsp;is, the voice. In psychoanalysis, the voice as such was elevated to the level of the object of desire, referred to as object (a).”<a href="#sdfootnote13sym" name="sdfootnote13anc"><sup>13</sup></a> The detachment of the image from&nbsp;the specific people producing speech and the accompanying spatial separation allows us to turn our attention to the voice itself, along&nbsp;with its irreducible surplus. This&nbsp;process, not unlike&nbsp;the selfless relationship between&nbsp;the gesture and attempts to explain the image in action, described previously in this&nbsp;article, facilitated the creation of an interesting web of cognitive processes during&nbsp;the symposium. The content created there was not authoritative in nature, as it operated in a&nbsp;performative structure that&nbsp;decentralized power centers and ostentatiously revealed the mechanisms that&nbsp;potentially lead to their formation, thus providing ample room for&nbsp;negotiation. By the same token, it enabled a&nbsp;homeostasis between&nbsp;individual media while respecting the difference inherent to each of them.</p>  </section>  <div class="clearfix"></div>

				<div class="m-footnotes"><p><a href="#sdfootnote1anc" name="sdfootnote1sym">1</a>Sergey Volkonsky, Człowiek wyrazisty. Sceniczne wychowanie gestu (według Delsarte’a), trans. Mieczysław Szpakiewicz (Warsaw: Księgarnia I. Rzepeckiego, 1920), 70.</p>
<p><a href="#sdfootnote2anc" name="sdfootnote2sym">2</a>The participants of the symposium were: Rafał Milach, Anna Nałęcka, and Joanna Kinowska; Paweł Bownik and Weronika Szczawińska; Aneta Grzeszykowska, Jan Smaga, and Katarzyna Bojarska; Elżbieta Janicka, Wojciech Wilczyk, and Waldemar Baraniewski; Michał Kaczyński, Łukasz Gorczyca, and Paweł Szypulski; Kuba Mikurda and Nicolas Grospierre; and Krzysztof Pijarski.</p>
<p><a href="#sdfootnote3anc" name="sdfootnote3sym">3</a>From the announcement of the symposium. Quoted from <a href="https://zacheta.art.pl/en/kalendarz/sympozjum?setlang=1" target="_blank" rel="noopener">http://zacheta.art.pl/en/kalendarz/sympozjum?setlang=1</a>, accessed October 8, 2016.</p>
<p><a href="#sdfootnote4anc" name="sdfootnote4sym">4</a>Bertolt Brecht, Gestik, in: Paweł Mościcki, Polityka teatru. Eseje o sztuce angażującej (Warsaw: Wydawnictwo Krytyki Politycznej, 2008), 71.</p>
<p><a href="#sdfootnote5anc" name="sdfootnote5sym">5</a>Cf. Andrew Hewitt, Social choreography: Ideology and Performance in Dance and Everyday Movement (Durham and London: Duke University Press, 2005).</p>
<p><a href="#sdfootnote6anc" name="sdfootnote6sym">6</a>Giorgio Agamben, “Notes on Gesture” in Means Without End: Notes on Politics, trans. Vincenzo Binetti, Cesare Casarino (Minneapolis: University of Minnesota Press, 2000), 57.</p>
<p><a href="#sdfootnote7anc" name="sdfootnote7sym">7</a>Ibid., 58.</p>
<p><a href="#sdfootnote8anc" name="sdfootnote8sym">8</a>Ibid., 56.</p>
<p><a href="#sdfootnote9anc" name="sdfootnote9sym">9</a>Cf. Philip Auslander, “The Performativity of Performance Documentation,” PAJ: A Journal of Performance and Art 3 (2006), 2.</p>
<p><a href="#sdfootnote10anc" name="sdfootnote10sym">10</a>Ibid.</p>
<p><a href="#sdfootnote11anc" name="sdfootnote11sym">11</a>Ibid., 3–4.</p>
<p><a href="#sdfootnote12anc" name="sdfootnote12sym">12</a>W.J.T. Mitchell, “There Are No Visual Media,” in Sound, ed. Caleb Kelly (London–Massachusetts: Whitechapel Gallery, MIT Press, 2011), 76.</p>
<p><a href="#sdfootnote13anc" name="sdfootnote13sym">13</a>Ewelina Godlewska-Byliniak, Teatr radio-logiczny Tymoteusza Karpowicza (Warsaw: Wydawnictwa Uniwersytetu Warszawskiego, 2012), 32.</p></div>

				
	<div class="m-doi" style="margin-bottom: 2em;">
		<a class="c-issue-toc__article-collapse-btn" role="button" data-toggle="collapse" href="#collapseDoi914" aria-expanded="false" aria-controls="collapseDoi914" data-lexicon-show="" data-lexicon-hide="">
			DOI
		</a>
		<div class="c-issue-toc__article-collapse collapse" id="collapseDoi914">
			<div class="c-issue-toc__article-collapse-inner">
				<div class="m-doi__content u-typo">
	<a href="https://doi.org/10.36854/widok/2015.12.914" target="_blank">https://doi.org/10.36854/widok/2015.12.914</a>
				</div>
			</div>
		</div>
	</div>
	

				
	<div class="m-bibliography" style="margin-bottom: 2em;">
		<a class="c-issue-toc__article-collapse-btn" role="button" data-toggle="collapse" href="#collapseSummary914" aria-expanded="false" aria-controls="collapseSummary914" data-lexicon-show="" data-lexicon-hide="">
			Bibliography
		</a>
		<div class="c-issue-toc__article-collapse collapse" id="collapseSummary914">
			<div class="c-issue-toc__article-collapse-inner">
				<div class="m-bibliography__content u-typo">
	<p>Wołkoński, Sergiusz. <em>Człowiek wyrazisty. Sceniczne wychowanie gestu (według Delsarte’a)</em>. Translated by M. Szpakiewicz. Warszawa: Księgarnia I. Rzepeckiego, 1920.</p>
<p>Mościcki, Paweł. <em>Polityka teatru. Eseje o sztuce angażującej</em>. Warszawa: Wydawnictwo Krytyki Politycznej, 2008.</p>
<p>Hewitt, Andrew. <em>Social choreography: Ideology and Performance in Dance and Everyday Movement</em>. Durham and London: Duke University Press, 2005.</p>
<p>Agamben, Giorgio. “Uwagi o geście”. Translated by P. Mościcki. In <em>Agamben. Przewodnik Krytyki Politycznej</em>. Warszawa: Wydawnictwo Krytyki Politycznej, 2010.</p>
<p>Auslander, Philip. “The Performativity of Performance Documentation”. <em>PAJ: A Journal of Performance and Art</em> 3 (2006).</p>
<p>Mitchell, W.J.T. <em>There Are No Visual Media</em>. In <em>Sound</em>. Edited by C. Kelly. London-Cambridge, Mass.: Whitechapel Gallery, MIT Press, 2011.</p>
<p>Godlewska-Byliniak, Ewelina. <em>Teatr radio-logiczny Tymoteusza Karpowicza</em>. Warszawa: Wydawnictwa Uniwersytetu Warszawskiego, 2012.</p>
<p> </p>
				</div>
			</div>
		</div>
	</div>
	

			</article>
		</div>
	</div>
</div>

</main>

[!evoSystemInfo?&theme=`dark`!]

<script>
	
	

	
	/*var Hyphenopoly = {
		require: {
			"pl": "Przeintelektualizować",
			"en-us": "Supercalifragilisticexpialidocious"
		},
		setup: {
			selectors: {
				".m-article .u-typo p": {},
				".m-article .u-typo li": {}
			}
		}
	};*/

</script>
<!--<script src="Hyphenopoly/Hyphenopoly_Loader.js"></script>-->

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<!-- <script>window.jQuery || document.write('<script src="assets/templates/widok_tpl/js/vendor/jquery-2.2.4.min.js"><\/script>')</script> -->
<script>window.jQuery || document.write('<script src="assets/templates/widok_tpl/js/vendor/jquery-1.12.4.min.js"><\/script>')</script>

</body>
</html>